name: Selenium Test Workflow
on: push
jobs:
  Selenium_Test_Job1:
    name: Selenium Test Job
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is running inside a ${{ runner.os }} server in GitHub"
      - name: Check out source code
        uses: actions/checkout@v3.5.2
      - run: echo "This repo is ${{ github.repository }}."
      - name: Run an inline script
        run: |
          mkdir newfolder
          ls -l
